name: Prison

author: kodirati
website: kodirati.com
description: Used as the core for the prison server of Evil Kingdom.

main: net.evilkingdom.prison.Prison
version: ${git.commit.id.describe-short}
api-version: 1.18
depend: [Commons, Basics]

commands: